### ISSUE TITLE
Add 'force-batch-now' command to periodic jobs

### ISSUE THREAD

**Issue by jrasell** [jrasell/levant#107]
**Description**

During code releases of jobs which are periodic, it may be preferable for operators to execute a run of the job immediately rather than waiting for the scheduled execution. Nomad provides this option via the [API](https://www.nomadproject.io/api/jobs.html#force-new-periodic-instance), so this would be adding a flag to the deploy command.

**Comment by stevenscg** [comment]
I wasn't aware of this option on the API, but it seems really useful for some cases.
