### ISSUE TITLE
[FEATURE] Canary workflow enhancements with auto-promote

### ISSUE THREAD

**Issue by mimato** [jrasell/levant#15]
Hi Folks,

Levant is perfect for our rolling deploy workflow, and we're trying it out at the moment, but we also have a canary workflow where we do `canary app -> wait 5-10 mins -> promote canary`. I'm wondering if this is something you would consider accepting in to Levant and if so, whether you think it should be an addition to `levant deploy` like `levant deploy -canary=300s` or a new command like `levant canary -wait=300s`

Thanks!

**Comment by ericwestfall** [comment]
@mimato When you deploy a canary and wait, are you running some test mechanism against the canary to determine whether to promote/fail?

**Comment by mimato** [comment]
We basically use our production monitoring to page us if the canary is bad - if metrics are bad or if there are errors in the logs.

**Comment by jrasell** [comment]
hey @mimato thanks for the request. I just had a quick chat with @ericwestfall and we think this would be a good addition to Levant. I would love to get any feedback you have on the proposed implementation:

- Levant will use a flag `canary-wait-time` under the deploy command which specifies a time in seconds that Levant will hold before auto-promoting a canary job
- If the user uses the flag without a canary configured job, Levant will exit
- Levant will render and register the job if possible, and then watch the deployment for any signals from Nomad
- If the deployment is failed by a user, Levant will be notified and exit
- If the wait-time is reached, Levant will check to confirm the canary is passing health-checks and then promote
- Levant will watch the promotion to confirm success before exiting

If you and @ericwestfall think this sounds appropriate or have any feedback please let me know and I will take a look at starting this tonight

**Comment by ericwestfall** [comment]
That all sounds good to me @jrasell, a small suggestion though. I think naming the flag something like `canary-auto-promote=300` makes it easier to know what the flag is doing. Just a suggestion, either way seems cool to me.

**Comment by mimato** [comment]
The implementation looks good to me, and I like @ericwestfall's suggestion about the flag name.
