### ISSUE TITLE
Deployment successful log message changed after v0.0.4

### ISSUE THREAD

**Issue by stevenscg** [jrasell/levant#159]
**Description**

It appears that the log level used for the "deployment successful" log message changed between 0.0.4 and 0.1.0.

For some time on 0.0.4, I have used `-log-level=error` on my CI builds to cut down on the noise. This resulted in very little output per job deployed, which was desirable.

As of 0.1.0, this log output is no longer present when using `error` log level:
```
[INFO] levant/command: deployment of job api successful
```

Given the presence of the `[INFO]` tag in that message as of 0.0.4, I suspect that the correct log level checks were added sometime after 0.0.4 and the lack of this message when using log-level `error` is probably the more correct behavior.

I've found that this is a useful message to have emitted. If there's a way to categorize it that keeps the noise level low, I'd be a big fan of that! That said, and if changes are being made, I tend to think that the log output for the variable lookups falls more into a `DEBUG` log level than `INFO`.

**Output of `levant version`:**

```
0.1.0
```

**Comment by jrasell** [comment]
@stevenscg this log was coming from the UI logger which I have changed and plan to changed further just to use the zerolog logger rather than that from the UI.

I quite like having the variables substitutions as INFO as these are changes/updates/actions happening; happy to discuss further though and would be interested in your additional thoughts.

**Comment by stevenscg** [comment]
@jrasell Fair point. INFO for the variable substitutions is probably fine and likely the best option. I can live with the extra output at the INFO level. I can't think of a better solution right now that stays within the available logging levels.
