### ISSUE TITLE
Render command log level

### ISSUE THREAD

**Issue by sblargaba** [jrasell/levant#228]
**Description**
When invoking levant with the render command, it behaves as if the flag `-log-level debug` was set.
Trying to explicitely set the flag causes the program to print the help message and exit with code 1

In my user case I'm running levant in a Jenkins job and injecting some sensitive data in the template: to prevent said data from being exposed I would need to hide the output by setting an higher log level like it can be done when calling `levant deploy`

**Output of `levant version`:**
```
/usr/bin # levant version
Levant v0.2.2
Date: 2018-08-06T09:05:20Z
Commit: df0fe5759617805430bd847d9d445ff9a65b01c6
Branch: 0.2.2
State: 0.2.2
Summary: df0fe5759617805430bd847d9d445ff9a65b01c6
```

**Comment by jrasell** [comment]
thanks @sblargaba; i'll take a look into this shortly for you.

**Comment by jrasell** [comment]
hi @sblargaba the render command doesn't have a logging level flag because it only either print an error when performing the render or the rendered job file.

**Comment by sblargaba** [comment]
Hey @jrasell the behaviour you're descripting is correct for the render command when considering the `stdout` but it would appear that the logging messages happens on the `stderr`. 
I also forgot to add that I'm using the `-out flag` to write into a file, which appears to redirect the stdout

For more clarity this is what I'm running within the [docker container ](https://hub.docker.com/r/jrasell/levant/)
```example
levant render -var-file=ops/parameters/ci.yml ops/nomad/execute-command.hcl
json logging level info on stderr, rendered file on stdout
levant render -var-file=ops/parameters/ci.yml -out /tmp/test.hcl ops/nomad/execute-command.hcl
json logging level info on stderr, rendered file on /tmp/test.hcl
```
Right now I'm redirecting the stderr to `/dev/null` to avoid exposing secrets, but I'd loose any error message that way

**Comment by jgarcia1990** [comment]
Hey @jrasell  !
I say the same , when doing a levant render there's no way to avoid all that big output, it goes to stdout and also stderr...so I'm also using &> dev/null. 
But if an error happens I won't be able to detect it. 

Could a fix be implemented?

Thanks!
