### ISSUE TITLE
Unique environment variable on each allocation

### ISSUE THREAD

**Issue by vvitayau** [jrasell/levant#254]
**Description**

Trying to work around a nomad limitation yet unresolved.
( https://github.com/hashicorp/nomad/issues/1185 )

I'm using levant/nomad to deploy zookeeper where each allocation requires a unique environment variable called myid (range [1..255) 

I encounter issues using ``[[ or (env "myid") "1" ]]`` to access this environment variable defined in /etc/environment. The render/allocation ends up using the same value across deployment.  
 
I could use ${NOMAD_ALLOC_INDEX} but can't without performing +1 arithmetic because that range is 0..(count-1), otherwise
```
[2018-11-06 18:26:02,846] ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain)
java.lang.RuntimeException: My id 0 not in the peer list
```

**Relevant Nomad job specification file**

```
job "cp-zookeeper" {
  region      = "global"
  datacenters = [ "[[ consulKeyOrDefault "services/zookeeper/datacenters" "dc1" ]]" ]
  type        = "service"
  priority    = 100
  group "confluent" {
    constraint {
      operator = "distinct_hosts"
      value    = "true"
    }
    count      =  [[ consulKeyOrDefault "services/zookeeper/count" "3" ]]
    task "zookeeper" {
      driver = "docker"
      config {
        # https://github.com/confluentinc/cp-docker-images/tree/5.0.0-post/debian/zookeeper
        image       = "confluentinc/cp-zookeeper:5.0.0"
        dns_servers = ["169.254.1.1"]
        port_map {
          zk = 2181
          peer = 2888
          election = 3888
        }
      }
      service {
        port = "zk"
      	name = "zookeeper"
        tags = [
        ]
      }
      env {
        ZOOKEEPER_SERVER_ID = "${NOMAD_ALLOC_INDEX}"

        # https://github.com/confluentinc/cp-docker-images/blob/5.0.0-post/debian/zookeeper/include/etc/confluent/docker/zookeeper.properties.template
        ZOOKEEPER_CLIENT_PORT = 2181

        # https://github.com/confluentinc/cp-docker-images/blob/5.0.0-post/debian/zookeeper/include/etc/confluent/docker/zookeeper.properties.template#L39
        ZOOKEEPER_SERVERS = "foo.zookeeper.service.consul:2888:3888;bar.zookeeper.service.consul:2888:3888;baz.zookeeper.service.consul:2888:3888"
      }
      resources {
        cpu    = [[ consulKeyOrDefault "services/zookeeper/resources/cpu" "100" ]]
        memory = [[ consulKeyOrDefault "services/zookeeper/resources/memory" "512" ]]
        network {
          mbits = [[ consulKeyOrDefault "services/zookeeper/resources/network/mbits" "10" ]]
          port "zk" { static = 2181 }
          port "peer" { static = 2888 }
          port "election" { static = 3888 }
        }
      }
    }
  }
}
```

**Output of `levant version`:**

```
Levant v0.2.5
Date: 2018-10-25T13:24:11Z
Commit: 0514741514e70caf82976c2c67f98414046b2392
Branch: 0.2.5
State: 0.2.5
Summary: 0514741514e70caf82976c2c67f98414046b2392
```

**Output of `nomad version`:**

```
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
```

**Comment by jrasell** [comment]
Hey @vvitayau thanks for opening this issue, it's quite an interesting one. I'll try to help but Levant almost certainly can't help here as it has no control over the allocations and placement; the templating is done before submitting the job to Nomad. One potential solution I could think of would be to have 3 separate groups, each configuring a single zookeeper instance. This way you could statically set the `myid` value as needed and incremented across each instance.

**Comment by vvitayau** [comment]
Closing ticket, figured out a solution where I can create my own counter service 
```
    consul kv put services/nginx/volumes 'volumes = [ "/vagrant/tmp:/usr/share/nginx/html:ro" ]'
    levant deploy /vagrant/nomad/nginx.nomad

    consul kv put "services/zookeeper/artifact/source" 'http://nginx.localhost/xxx'
    levant deploy /vagrant/nomad/zookeeper.nomad
```

OR

I figured out a solution by  one-time setup a unique value to be uniquely load at runtime
range 1..255 on each zookeeper machine.
```
    sudo mkdir -p /var/lib/zookeeper/data
    echo -n 1 | sudo tee /var/lib/zookeeper/data/myid
```

then I have my nomad hcl to load above value
```
    task "zookeeper" {

      template {
        env = false
        destination = "${NOMAD_ALLOC_DIR}/data/myid"
        data        = <<EOH
{{ file "/var/lib/zookeeper/data/myid" }}
EOH
      }

      template {
        env         = false
        destination = "local/zookeeper.properties"
        data        = <<EOH
...
[[ consulKeyOrDefault "services/zookeeper/servers/1" "server.1=zookeeper-0.zookeeper.service.consul:2888:3888" ]]
EOH
      }

      ...

      service {
        port = "zk"
        name = "zookeeper"
        tags = [
          "zookeeper-${NOMAD_ALLOC_INDEX}"
        ]
        ...
```

**Comment by vvitayau** [comment]
Ignore dynamically assign tags above ... 
quorum can't be reached because it can not connect to the zookeeper instance on startup since
consul registration is done after the service is up and running. It will appear like the service is running.

However to confirm https://issues.apache.org/jira/browse/ZOOKEEPER-2164 symptoms
```
$ telnet zookeeper-0.zookeeper.service.consul 2181
Escape character is '^]'.
stat
This ZooKeeper instance is not currently serving requests
```

Solution: on each machine assign it manually
$ sudo vi /etc/consul.d/zookeeper.json
{"service": {"name": "zookeeper", "tags": ["zookeeper-xxx"], "port": 2181}}
```

**Comment by vvitayau** [comment]
Changed to 
```
      template {
        env = false
        destination = "${NOMAD_ALLOC_DIR}/data/myid"
        source      = "/etc/nomad/myid"
      }
```

Otherwise 

`Template failed: (dynamic): execute: template: :1:3: executing "" at <file "/etc/nomad/myid">: error calling file: '/etc/nomad/myid' is outside of sandbox`
