### ISSUE TITLE
Pass Vault token to Nomad

### ISSUE THREAD

**Issue by redfive** [jrasell/levant#255]
We use Nomad in conjunction with Vault and require Vault Tokens for deployment. But we have no way to pass those tokens through Levant so they can be used by Nomad.

Would like to see Levant pass along the already present VAULT_TOKEN env variable, or at the very least allow it as a CLI flag.

**Relevant Nomad job specification file**

```
.hcl file:
  vault {
    policies = "my-vault-policy"
  }
```

**Output of `levant version`:**

```
Levant v0.2.5
Date: 2018-10-31T18:46:18Z
Commit: effb4e3
Branch: HEAD
State: clean
Summary: effb4e3
```

**Output of `consul version`:**

```
Consul v1.1.0-1-gda72a278
```

**Output of `nomad version`:**

```
Nomad v0.8.4+ent (806c7a42398568f7ad91cf33daff47a41189fb8a)
```

**Additional environment details:**
```
Nomad config:
vault {
    enabled = true
    address = "https://vault.service.consul:8200"
    allow_unauthenticated = true
}

**Comment by jrasell** [comment]
hey @redfive; when configuring a Nomad job with a Vault stanza, the Nomad client will make the Vault token available to the task by writing it to the secret directory at `secret/vault_token` and by injecting a `VAULT_TOKEN` environment variable. Therefore this behaviour is already present in Nomad and available for you.

additional reading - https://www.nomadproject.io/docs/job-specification/vault.html

**Comment by redfive** [comment]
Hi @jrasell, yes, If you have a policy associated with a task Nomad will inject that token. I'm talking about gating access to Nomad itself, as detailed here: https://www.nomadproject.io/docs/configuration/vault.html#allow_unauthenticated

We require authentication in the form of a Vault token, that is attached to the policy in the Job Spec. Our calls to Nomad look like: `nomad run -vault-token=<token> jobspec.hcl`. Nomad then verifies that token has access to the policy named in the Vault stanza in the jobspec.

**Comment by gjergjsheldija** [comment]
hi @redfive 
i think i'm having the same issue. where when i deploy with levant i get the error message `Unexpected response code: 500 (rpc error: Vault policies requested but missing Vault Token)`, but when i deploy with nomad setting the VAULT_TOKEN variable the deployment is successful

**Comment by gjergjsheldija** [comment]
hi, 
this fixed it https://github.com/jrasell/levant/pull/258
