### ISSUE TITLE
Update config to allow TLS config passing

### ISSUE THREAD

**Issue by jrasell** [jrasell/levant#29]
In order to work in certain situations; it would be useful if Levant allows the user to pass TLS certificate details on deployment including the following:

 * ca-cert 
 * cert
 * cert-key

**Comment by dropje86** [comment]
As far as I can tell this should already work.
```
func NewNomadClient(addr string) (NomadClient, error) {
	config := nomad.DefaultConfig()
```
This returns a defaultconfig from github.com/hashicorp/nomad/api which parses the following ENV vars:
```
NOMAD_ADDR (Nomad HTTP API endpoint)
NOMAD_HTTP_AUTH (basic auth username:password)
NOMAD_CACERT (path to a PEM-encoded CA cert file )
NOMAD_CAPATH (path to a directory of PEM-encoded CA cert files)
NOMAD_CLIENT_CERT (path to the client certificate)
NOMAD_CLIENT_KEY (path to the client key)
NOMAD_SKIP_VERIFY (enable or disable verification; (true|1) / (false|0) )
```
