### ISSUE TITLE
Injecting environment variables for spring boot

### ISSUE THREAD

**Issue by rawadrifai** [jrasell/levant#301]
This is a *Question*:
I am filling a devops resource we lost. He's the only one that knows how to use levant.
I couldn't find my answer online so I'm trying here. 
I am deploying a spring boot app using levant. I would like to inject environment variables. Is that done through levant.yml file? does it take it as is and inject them?

**Comment by jrasell** [comment]
@rawadrifai does the template contain variables which should be populated from environment variables as described [here](https://github.com/jrasell/levant/blob/master/docs/templates.md#env) or something else?

**Comment by rawadrifai** [comment]
@jrasell we're good.. there was a .hcl nomad config file that maps environment variables injected through jenkins into the application. Thank you!
