### ISSUE TITLE
Update Nomad to 0.9.2+

### ISSUE THREAD

**Issue by andyghiuta** [jrasell/levant#309]
**Description**
Nomad introduced `auto_promote` option for canary deployments in 0.9.2:
https://www.nomadproject.io/docs/job-specification/update.html#auto_promote
https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#092-june-5-2019
https://github.com/hashicorp/nomad/pull/5719

**Relevant Nomad job specification file**

```
job "jobname" {
  region = "us"
  datacenters = [
    "dc1"
  ]
  type = "service"
  group "deployment" {
    count = 3
    update {
      canary = 3
      max_parallel = 1
      auto_revert = true
      auto_promote = true
    }
  }
}
```

**Output of `levant version`:**

```
$ levant -v
Levant v0.2.7
Date: 2019-03-19T08:26:24Z
Commit: 9e952d55f171e63f5c7955e826401eac91ed0b28
Branch: 0.2.7
State: 0.2.7
Summary: 9e952d55f171e63f5c7955e826401eac91ed0b28
```

**Debug log outputs from Levant:**

```
[ERROR] levant/command: error parsing 'job': 1 error occurred:

* group: update -> invalid key: auto_promote
```

**Comment by pznamensky** [comment]
@jrasell could you please help with it?

**Comment by andyghiuta** [comment]
It looks like updating to 0.9.6 was not sufficient. I'm receiving the same error:
```
[ERROR] levant/command: error parsing 'job': 1 error occurred:

* group: update -> invalid key: auto_promote

**Comment by jrasell** [comment]
@andyghiuta I will need to release 0.2.9 in order for the vendor change to take affect. You can build master locally if needed in the meantime. I hope to find time to perform the release this week, hopefully tomorrow.

**Comment by andyghiuta** [comment]
Ah, right... I was looking at the 0.2.8 release date (14th) and thought "that was 11 days ago, when this was closed.". I forgot to check the month too. Monday... 😬

**Comment by andyghiuta** [comment]
@jrasell I tested a build from master and it works as expected. An official release would be much appreciated. Thanks!
