### ISSUE TITLE
missing support for meta in service stanza

### ISSUE THREAD

**Issue by yossisal** [jrasell/levant#310]
**Description**

Service Stanza now includes an optional meta field. However, this is not supported by levant:

**Relevant Nomad job specification file**

```
[ERROR] levant/command: error parsing 'job': 1 error occurred:
* group: '...., task: '...', service (0) -> invalid key: meta
```

**Output of `levant version`:**

```
Levant v0.2.8
Date: 2019-09-14T14:09:17Z
Commit: dee2715dbc6bd4c8c3d73c882e017e380782e1d2
Branch: 0.2.8
State: 0.2.8
Summary: dee2715dbc6bd4c8c3d73c882e017e380782e1d2
```

**Output of `consul version`:**

```
Consul v1.5.3
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)

```

**Output of `nomad version`:**

```
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)
```

**Additional environment details:**

**Debug log outputs from Levant:**

**Comment by ath0s** [comment]
I still get this error for the meta tag when using Levant 0.2.9

**Comment by jrasell** [comment]
@ath0s from a glance, it looks like your job-spec is incorrect as the service stanza does not support the meta key. The meta key support is detailed - https://www.nomadproject.io/docs/job-specification/meta.html

If you could share a redacted version of the file I can confirm this if you want.

**Comment by ath0s** [comment]
@jrasell thank you for your quick response.
the service stanza should support the meta key according to https://www.nomadproject.io/docs/job-specification/service.html#meta
However, I might have been too quick to blame this on Levant. I think my error might be because on an old Nomad version on my end. Sorry about that.
