### ISSUE TITLE
Update Nomad to 0.10.x

### ISSUE THREAD

**Issue by rkettelerij** [jrasell/levant#315]
To support host volumes in jobspecs.

**Comment by rkettelerij** [comment]
I've taken a look at this and tried to update the vendored Nomad to 0.10.1. But now levant fails to build due to compile errors on `vendor/github.com/hashicorp/nomad/nomad/structs/structs.generated.go`. Might be related to https://github.com/hashicorp/nomad/issues/6537.

@jrasell perhaps you can take a look?

**Comment by jrasell** [comment]
@rkettelerij I am also getting this on another build; so will be looking into it.

**Comment by jrasell** [comment]
this should now be resolved.
