### ISSUE TITLE
Replace function not found on the master build using nomad 0.10.0

### ISSUE THREAD

**Issue by dracmic** [jrasell/levant#321]
Hello, 

I am using nomad 0.10.0 and on levant with build from master branch I get following error:

[ERROR] levant/command: template: jobTemplate:55: function "replace" not defined 

On line 55 and 56 I have:
     "local_service_address": "{{ env "NOMAD_IP_[[ replace .job.name "-" "_" ]]_service_http" }}",
    "local_service_port": {{ env "NOMAD_PORT_[[ replace .job.name "-" "_" ]]_service_http" }},

Did somehow the replace function was erased? If it is like so please help me to fix it.

Best regards.

**Comment by dracmic** [comment]
Hello J.,

You did include the replace function of raffaelpirrolla but now the nomad structs 0.10.0 doesn't work anymore :(.
Compiling with golang 1.13.3.

I get :


Best regards.

**Comment by jrasell** [comment]
hi @dracmic could you provide an example I can test with locally to reproduce this? As you have stated, the replace function was not merged into Levant, so would not have worked unless you were using a build based on that specific PR.

**Comment by dracmic** [comment]
Hello jrasell,
 Here is the template I am using:
job "[[.job.name]]" {
  region = "global"

  datacenters = [[ with (index .job .envName) ]][[ .datacenters ]][[ end ]]

  type = "service"

  update {
    stagger = "20s"
    max_parallel = SERVICE_COUNT_REPLACEMENT
    min_healthy_time = "30s"
    health_check = "checks"
    healthy_deadline = "4m"
    canary = 1
    auto_revert       = true
  }

  priority = 100

  constraint {
    attribute = "${node.class}"
    value = "[[.job.class]]"
  }

  group "[[.job.name]]-group" {
    count = SERVICE_COUNT_REPLACEMENT

    ephemeral_disk {
      size = "3000"
    }
    volume "certs-ui" {
      type = "host" {
        read_only = true
        source = "certs"
      }
    }
    task "[[.job.name]]-proxy" {

    volume_mount {         
     volume      = "certs-ui"         
     destination = "/etc/consul.d/ssl/"      
     }
      driver = "exec"

    template {
        data = <<EOH
{
  "kind": "connect-proxy",
  "name": "[[.job.name]]-proxy",
  "id": "[[.job.name]]-proxy-UUID_PLACEHOLDER",
  "port": {{ env "NOMAD_HOST_PORT_http_proxy" }},
  "proxy": {
    "destination_service_name": "[[.job.name]]-service",
    "destination_service_id": "NOMADID_PLACEHOLDER",
    "local_service_address": "{{ env "NOMAD_IP_[[ replace .job.name "-" "_" ]]_service_http" }}",
    "local_service_port": {{ env "NOMAD_PORT_[[ replace .job.name "-" "_" ]]_service_http" }},
    "upstreams": [
      [[ $i := 0 ]]
      [[ if (index .job .envName "resources") ]]
      [[ if (index .job .envName "resources" "redis") ]]
      [[ range $key, $value := (index .job .envName "resources" "redis") ]]
      [[ if ne $i 0 ]],[[ end ]]
      {
        "destination_name": "[[ $key ]]-service",
        "local_bind_address": "{{ env "NOMAD_IP_[[ replace $key "-" "_" ]]" }}",
        "local_bind_port": {{ env "NOMAD_PORT_[[ replace $key "-" "_" ]]" }}
      }
      [[ $i == 1 ]]
      [[ end ]]
      [[ end ]]
      [[ if (index .job .envName "resources" "http") ]]
      [[ range $key, $value := (index .job .envName "resources" "http") ]]
      [[ if ne $i 0 ]],[[ end ]]
      {
        "destination_name": "[[ $key ]]-service",
        "local_bind_address": "{{ env "NOMAD_IP_[[ replace $key "-" "_" ]]" }}",
        "local_bind_port": {{ env "NOMAD_PORT_[[ replace $key "-" "_" ]]" }}
      }
      [[ $i == 1 ]]
      [[ end ]]
      [[ end ]]
      [[ end ]]
    ],
    "config": {
      "envoy_public_listener_json": "
      {
        \"@type\": \"type.googleapis.com/envoy.api.v2.Listener\",
        \"name\": \"public_listener:{{ env "NOMAD_ADDR_http_proxy" }}\",
        \"address\": {
          \"socketAddress\": {
            \"address\": \"{{ env "NOMAD_IP_http_proxy" }}\",
            \"portValue\": {{ env "NOMAD_PORT_http_proxy" }}
          }
        },
        \"filterChains\": [
          {
            \"filters\": [
              {
                \"name\": \"envoy.http_connection_manager\",
                \"config\": {
                  \"stat_prefix\": \"ingress_[[.job.name]]\",
                  \"route_config\": {
                    \"name\": \"local_route\",
                    \"virtual_hosts\": [
                      {
                        \"name\": \"[[.job.name]]\",
                        \"domains\": [\"*\"],
                        \"routes\": [
                          {
                            \"match\": {
                              \"prefix\": \"/\"
                            },
                            \"route\": {
                              \"cluster\": \"local_app\"
                            }
                          }
                        ]
                      }
                    ]
                  },
                  \"http_filters\": [
                    {
                      \"name\": \"envoy.router\",
                      \"config\": {}
                    }
                  ]
                }
              }
            ]
          }
        ]
      }"
    }
  }
}
        EOH

        destination = "${NOMAD_TASK_DIR}/proxy.json"
      }

      template {
        data = <<EOH
        CONSUL_HTTP_ADDR = 'https://127.0.0.1:8501'
        CONSUL_GRPC_ADDR = '127.0.0.1:8502'
        CONSUL_CACERT = '{{ env "NOMAD_SECRETS_DIR" }}/ca.crt'
        CONSUL_CLIENT_CERT = '{{ env "NOMAD_SECRETS_DIR" }}/consul.crt'
        CONSUL_CLIENT_KEY = '{{ env "NOMAD_SECRETS_DIR" }}/consul.key'
        EOH

        destination = "${NOMAD_TASK_DIR}/temp.env"
        env         = true
      }

      template {
        data = <<EOH
import sys
import signal
import requests
import uuid
import re
import time
import subprocess

try:
  uid = uuid.uuid4()
  nomadid = 0
  retry = 0

  deregister_url = 'https://127.0.0.1:8501/v1/agent/service/deregister/[[ .job.name ]]-proxy-' + str(uid)
  register_url = 'https://127.0.0.1:8501/v1/agent/service/register'
  services_url = 'https://127.0.0.1:8501/v1/agent/services'

  certs = ['{{ env "NOMAD_SECRETS_DIR" }}/consul.crt','{{ env "NOMAD_SECRETS_DIR" }}/consul.key']

  print('[info] getting consul ID for service [ [[ .job.name ]]-service ]', flush=True)
  time.sleep(5)
  while retry < 5:
    print('[info] trying: ' + str(retry), flush=True)
    if nomadid != 0:
      break
    response = requests.get(services_url, cert=certs, verify='{{ env "NOMAD_SECRETS_DIR" }}/ca.crt').json()
    for nomadkey in response:
      if response[nomadkey]["Port"] == {{ env "NOMAD_PORT_[[ replace .job.name "-" "_" ]]_service_http" }}:
        nomadid = nomadkey
        break

    retry = retry + 1
    time.sleep(10)

  if nomadid == 0:
    print('[error] after 50s timed out trying to find nomad allocation for job: [[ replace .job.name "-" "_" ]]', flush=True)
    exit(1)

  print('[info] rewriting JSON file.', flush=True)
  with open('{{ env "NOMAD_TASK_DIR" }}/final.json', "w") as f:
    for line in open('{{ env "NOMAD_TASK_DIR" }}/proxy.json'):
      line = re.sub(r'UUID_PLACEHOLDER', str(uid), line)
      line = re.sub(r'NOMADID_PLACEHOLDER', nomadid, line)
      line = re.sub('\s$', '', line)
      f.write(line)

  print('[info] registering the parsed JSON into consul', flush=True)
  r = requests.put(register_url, data=open('{{ env "NOMAD_TASK_DIR" }}/final.json', 'rb'), cert=certs, verify='{{ env "NOMAD_SECRETS_DIR" }}/ca.crt')
  if r.status_code != 200:
    print('[error] ' + r.text)
    exit(1)

  print('[info] executing consul connect for ' + nomadid, flush=True)
  subprocess.run(['consul', 'connect', 'envoy', '-sidecar-for', nomadid, '-admin-bind', '{{ env "NOMAD_IP_http_proxy" }}:{{ env "NOMAD_PORT_http_proxy" | parseUint | add 12001 }}'])

finally:
  print('[info] deregistering [[ .job.name ]]-proxy consul service')
  requests.put(deregister_url, cert=certs, verify='{{ env "NOMAD_SECRETS_DIR" }}/ca.crt')
EOH

        destination = "${NOMAD_TASK_DIR}/script.py"
      }

      config {
        command = "/usr/bin/python3"
        args    = ["${NOMAD_TASK_DIR}/script.py"]
      }

      resources {
        memory = 256
        network {
          port "http_proxy" {}
          [[ if (index .job .envName "resources") ]]
          [[ if (index .job .envName "resources" "redis") ]]
          [[ range $key, $value := (index .job .envName "resources" "redis") ]]
          port "[[ replace $key "-" "_" ]]" {}
          [[ end ]][[ end ]]
          [[ if (index .job .envName "resources" "http") ]]
          [[ range $key, $value := (index .job .envName "resources" "http") ]]
          port "[[ replace $key "-" "_" ]]" {}
          [[ end ]]
          [[ end ]]
          [[ end ]]
        }
      }
    }

    task "[[.job.name]]-service" {

    volume_mount {         
     volume      = "certs-ui"         
     destination = "/etc/consul.d/ssl/"      
     }
      driver = "java"

      # ¯\_(ツ)_/¯... I have tried not to use this, true story
      kill_signal = "SIGKILL"

      artifact {
        source = "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.1/jmx_prometheus_javaagent-0.3.1.jar",
        mode = "file"
        destination = "local/jmxagent.jar"
        options {
          archive = false
        }
      }

      artifact {
        source = "https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=co.elastic.apm&a=elastic-apm-agent&v=LATEST",
        mode = "file"
        destination = "local/apm-client.jar"
        options {
          archive = false
        }
      }

      template {
          data = <<EOH
---
  startDelaySeconds: 0
  ssl: false
  lowercaseOutputName: false
  lowercaseOutputLabelNames: false
EOH

           destination = "local/temp.yml"
      }

      template {
        data = <<EOH
          jmx_hostport={{ env "attr.unique.hostname" }}:{{ env "NOMAD_PORT_http" | parseUint | add 24002 }}
        EOH

        destination = "local/temp.env"
        env         = true
      }

      env {
        ARTIFACT_URL = "ARTIFACT_REPLACEMENT_URL"
        ENVIRONMENT = "[[.envName]]"
        # Stage memory parameters (MB), based ond the environment jenkins will select the stage or live memory parameters
        MEMORY_SELECT = "[[ with (index .job .envName) ]][[ .memory ]][[ end ]]"
      }

      artifact {
        source = "${ARTIFACT_URL}"
        destination = "local/[[.job.name]]-service"
      }

      config {
        jar_path = "local/[[.job.name]]-service/ARTIFACT_FULL_NAME_REPLACEMENT"
        jvm_options = [
          [[ $jobname := .job.name ]]
          [[ if (index .job .envName "resources") ]]
          [[ if (index .job .envName "resources" "redis") ]]
          [[ range $key, $value := (index .job .envName "resources" "redis") ]]
          [[ range $hostprop, $portprop := $value ]]
          "-D[[ $hostprop ]]=${NOMAD_IP_[[ replace $jobname "-" "_" ]]_proxy_[[ replace $key "-" "_" ]]}",
          "-D[[ $portprop ]]=${NOMAD_PORT_[[ replace $jobname "-" "_" ]]_proxy_[[ replace $key "-" "_" ]]}",
          [[ end ]][[ end ]][[ end ]]
          [[ if (index .job .envName "resources" "http") ]]
          [[ range $key, $value := (index .job .envName "resources" "http") ]]
          [[ range $urlprop, $pathprop := $value ]]
          "-D[[ $urlprop ]]=http://${NOMAD_IP_[[ replace $jobname "-" "_" ]]_proxy_[[ replace $key "-" "_" ]]}:${NOMAD_PORT_[[ replace $jobname "-" "_" ]]_proxy_[[ replace $key "-" "_" ]]}[[ $pathprop ]]",
          [[ end ]]
          [[ end ]]
          [[ end ]]
          [[ end ]]
          "-javaagent:/local/jmxagent.jar=${jmx_hostport}:/local/temp.yml",
          "-Dspring.profiles.active=${ENVIRONMENT}",
          "-javaagent:/local/apm-client.jar",
          "-Delastic.apm.service_name=[[ .job.name ]]-service",
          "-Delastic.apm.server_urls=http://elastic-apm.${ENVIRONMENT}.win.windeln-it.de:8200",
          "-Delastic.apm.application_packages=org.example",
          "-Xmx${MEMORY_SELECT}m",
          "-Xms${MEMORY_SELECT}m",
          "-Dserver.port=${NOMAD_PORT_http}",
          "-Dwindeln.tomcat.ajp-enabled=false",
          "-Dtomcat.ajp.enabled=false",
	        "-Dswagger-ui.hostname=[[.job.dns]]"
        ]
      }

      service {
        name = "[[.job.name]]-service"
        port = "http"

        tags = [
          "microservice",
          "[[.job.name]]"
        ]

        check {
          name = "[[.job.name]]-service-info"
          type = "script"
          command = "/usr/bin/curl"
          args = [
            "-f",
            "-s",
            "http://mon:qysys@localhost:${NOMAD_PORT_http}/internal/mon/info"]
            interval = "30s"
            timeout = "15s"
        }
      }

      logs {
        max_files = 10
        max_file_size = 100
      }

      resources {
        cpu    = [[ with (index .job .envName) ]][[ .cpu ]][[ end ]]
        memory = [[ with (index .job .envName) ]][[ .memory ]][[ end ]]

        network {
          mbits = [[ with (index .job .envName) ]][[ .network.mbits ]][[ end ]]
          port "http" {}
        }
      }
    }
  }
}

**Comment by jrasell** [comment]
@dracmic I believe you volume stanza is incorrect, and therefore failing Nomad job spec parsing.

You seem to have:
```
volume "certs-ui" {
      type = "host" {
            read_only = true
            source = "certs"
      }
}
```

The Nomad docs:
```
volume "certs" {
      type      = "host"
      source    = "ca-certificates"
      read_only = true
}
```

**Comment by dracmic** [comment]
Thanks @jrasell for help
