### ISSUE TITLE
Levant deploy on Nomad 0.10 with docker doesn't take count of group

### ISSUE THREAD

**Issue by dracmic** [jrasell/levant#326]
Hello,

I did tried numerous times to figure out from where this issues comes but I cannot figure out. I am using docker driver with type service. Even it renders correctly:
 group "job-name-group" {
    count = 2
    ephemeral_disk {
      size = "3000"
    }
to nomad it sends:
INF levant/deploy: using dynamic count 1 for group job-name-group job_id=job-name.
If I run renderized job with nomad run job-name.yaml it does the correct thing.
Could you help me out to fix this?

**Comment by dracmic** [comment]
I fixed it using -force-count

**Comment by thatsk** [comment]
it should be added in levant cli by default
if count is changing in nomad job it should take
