### ISSUE TITLE
[FEATURE] Connect Through Bastion / Jump Host

### ISSUE THREAD

**Issue by stevenscg** [jrasell/levant#45]
HashiConf 2017 follow-up....

This is a fantastic project and I can't wait to use it. I'm still surprised that some of these features aren't part of the nomad core, TBH.

I'm not sure if this is a "feature" request or a discussion item, but I'd be interested in hearing thoughts on it and see if I have an edge case or a mainstream one.

We have two primary deployment scenarios for our nomad applications:
1) Automatically via CI/CD service that is hosted *outside* of our datacenter (which is just a VPC on AWS), and
2) Operator-directed deployments when launching a new datacenter, DR, etc.

With our current templating and deployment system, ssh access through a bastion host is used to connect to datacenter and then to connect to the Nomad API running privately within the datacenter. This lets us use the consul DNS name for nomad (i.e. `http://http.nomad.service.consul:4646`) in the API url.

The job files are available *outside* of the datacenter (with the CI/CD service or the operator's workstation).

Both of the deployment scenarios I describe work if levant can access the job files locally and deploy the jobs into the remote datacenter(s).

I don't see any explicit support for this kind of thing in the project right now.

Is there some SSH proxy and tunneling magic that solves this without changing the project?

Is there native support for "communicators" in the low-level go libraries used by the project with configuration options that can be exposed? Packer has [communicators](https://www.packer.io/docs/templates/communicator.html) and we've used them in our workflows successfully.

**Comment by dropje86** [comment]
Hi @stevenscg 

A couple of options without introducing any SSH magic into levant:
* Depending on your CI/CD system you could run a "slave" inside your datacenter which you can target to run the deploy. Jenkins for example has SSH node support
* You could run an authenticating reverse proxy in front of the Nomad API and use the appropriate ENV vars to authenticate (`NOMAD_HTTP_AUTH`)
* Setup a local port forward:
  * `ssh -L4646:http.nomad.service.consul:4646 ${yourbastionhostname}`
  * `levant deploy -addr=localhost:4646 -var-file=<vars.tf> job.nomad`

**Comment by jrasell** [comment]
Hi @stevenscg and thanks for reporting. I have read through the details a couple of times and believe I have a good understanding of the workflow; but if I have misunderstood anything please let me know.

The current workflow I use both professionally and personally is the following:
* I store all Nomad job specification files and associated variable files within a single "control" repository.
* If running a deployment from my local machine where I do not have direct access to the Nomad API I create an SSH tunnel before running Levant.
* If running a deployment from a CI server; the job will firstly checkout the repository with the Nomad job specification files. My CI instances usually have direct access to the Nomad API and therefore can run Levant with the checked-out code without issue.

I also use Packer communicators to manipulate files on the target build machine and it would be possible to implement this in Levant, however, I am not convinced it *should* be put in. That being said I would like to hear your thoughts on my methods and also the information provide by @dropje86 .

**Comment by stevenscg** [comment]
Hi @dropje86 and thanks!
* Our CI/CD is a SaaS product, so it will always be remote. I know a bunch of folks run Jenkins in the datacenter, which makes this part real easy.
* I really like the flexibility of exposing the Nomad API and will probably look at that next.
* I have a local port forwarding setup based on your suggestion that I'm trialing right now. I'll post more on it here later.

Hi @jrasell 

I too wasn't sure that this communicator stuff *should* be in the project. Since I was getting ready to start using the project, wanted to bring it up and see if others had similar needs.

I'm trialing some port forwarding options right now, which look good so far. I'll add a follow-up comment here once I get happy with that.

Thanks for sharing your workflow.

**Comment by pmcatominey** [comment]
Hey @stevenscg,

Just chiming in with how I've dealt with this issue, we have a proxy running in our environments to provide access to the Nomad API among others. The proxy is secured with Basic Auth over TLS and a firewall rule restricts access to known IPs.

Using Levant / Nomad CLI for us is as simple as setting the `NOMAD_ADDR` environment variable like: `NOMAD_ADDR=https://user:pass@proxy.addr`

**Comment by stevenscg** [comment]
Thanks for the info, @pmcatominey. That sounds like a great solution. Very simple.
