### ISSUE TITLE
[BUG] Levant does not handle periodic job types properly

### ISSUE THREAD

**Issue by pmcatominey** [jrasell/levant#50]
While the `service` scheduler is the only one to properly support deployments, there is value in using levant to render job file templates, it should therefore support registering other scheduler type jobs.

Currently solved with the following:
```sh
levant render -var x=y job.nomad > rendered.nomad
nomad run rendered.nomad
```

**Comment by jrasell** [comment]
@pmcatominey quickly checking the `Deploy` functioning ordering the job will be [registered](https://github.com/jrasell/levant/blob/master/levant/deploy.go#L75) before the schedular type is [checked](https://github.com/jrasell/levant/blob/master/levant/deploy.go#L90) therefore a `system` job will be rendered and deployed via Levant as far as I can tell unless I am missing something?

Potentially this is just a case of adding some logging to describe in more detail what is happening?

**Comment by pmcatominey** [comment]
Actually I should have clarified that I've noticed this problem was with jobs of type `periodic`, I've assumed it would affect all jobs but it actually seems to be due to there not being an evaluation:

```
[INFO] levant/deploy: using dynamic count 1 for job backup-bot and group backup-bot
[INFO] levant/deploy: triggering a deployment of job backup-bot
[ERROR] levant/deploy: Unexpected response code: 500 (rpc error: eval lookup failed: index error: UUID must be 36 characters)
[ERROR] levant/command: deployment of job backup-bot failed
```

Can probably be fixed by just returning if there is no evaluation.

**Comment by jrasell** [comment]
Ah that makes sense. Do you have an example job file I could play with @pmcatominey so I can make sure the fix is correct?

**Comment by pmcatominey** [comment]
Sure!

```
job "echo" {
  datacenters = ["dc1"]
  type = "batch"

  periodic {
    cron = "* * * * *"
    prohibit_overlap = true
  }

  group "echo" {
    count = 1

    task "echo" {
      driver = "docker"
      config {
        image = "alpine"
        command = "echo $(date)"
      }

      resources {
        cpu    = 100
        network {
          mbits = 10
        }
      }
    }
  }
}
```
