### ISSUE TITLE
[FEATURE] Use Consul KV data for vars

### ISSUE THREAD

**Issue by stevenscg** [jrasell/levant#58]
#### Summary

Enhance `levant` to use data from Consul KV as variables when rendering nomad jobs.

#### Background

When an organization uses Consul KV as a configuration repository for applications running within a particular environment and datacenter, the ability to access this data when rendering and deploying nomad jobs is very appealing.

The configuration data in Consul KV is often backed by a version controlled git repository, loaded using a tool like `git2consul`, and already accounts for per-environment and per-region / per-datacenter differences.

When similar data is also required to render and deploy nomad jobs, we are faced with either fetching the data from Consul prior to calling `levant` or replicating the required data locally to `levant` in the form of disparate vars and/or vars files structured by environment and/or region.

A very simple `key` keyword could support many of the more common use cases without embedding or attempting to emulate full `consul-template` functionality:
```hcl
[[ key "config/serviceA/keyA" ]]
```

User feedback could help decide if support for just `key` is sufficient for the most common use cases. `keyOrDefault` is frequently useful as well.

Several new configuration items will be required to access the consul API whether running on the same host that is running levant or remotely. Following the patterns established by HashiCorp for consul environment variable and cli options should help users leverage their existing consul configuration settings.

The existing `-var` and `-var-file` should remain and can take precedence.

#### Examples

For each example, the syntax shown would be part of the nomad job file.

A dynamic job name for a service:
```hcl
job "[[ key "config/serviceA/nomad_job_name" ]]" {
  ....
}
```

The nomad region is a required attribute and deploys to multiple datacenters each need to specify a value for it:
```hcl
job "api" {
    type = "service"

    region = "[[ key "config/serviceA/nomad_region" ]]"
    datacenters = ["us1"]
```

Container registry and artifact paths are frequently dynamic and vary across projects and environments:
```hcl
job "api" {
    config {
        image = "[[ key "config/serviceA/nomad_registry_url" ]]:${NOMAD_META_VERSION}"
     }

     artifact {
         source = "[[ key "config/serviceA/nomad_artifact_url" ]]/${NOMAD_META_VERSION}/foo.tar.gz"
     }
```

**Comment by jrasell** [comment]
I certainly like this idea. I will look at trying to leverage Consul template for this if possible, however, if not I can add a template function which may be preferable as it opens up the possibility of adding addition functions (similar to Packer) in the future.

**Comment by mildred** [comment]
I just discovered your work, and internally we use [consul-template](https://github.com/hashicorp/consul-template) to template our nomad job files so they are slightly different for the dev environment, staging and production. It works really well, but it doesn't have all the other features you have that integrates to nomad.

Perhaps you can make use of consul-template too and you get a templating engine with consul key-value access for free, and all the features of consul-template (when a consul key changes, the template is regenerated and you can hook into that to execute a command: deploy on nomad for example)
