### ISSUE TITLE
Nomad acl tokens are not supported

### ISSUE THREAD

**Issue by leeuwenrjj** [jrasell/levant#75]
With nomad 0.7 you can close down the nomad api by use of ACLs

It seems levant does not use the available NOMAD_TOKEN in the environment nor will it accept the -token argument.

**Comment by jrasell** [comment]
@leeuwenrjj thanks for the report. I will work on updating the vendored version of Nomad which will allow use of the env variable. Is this enough, or is there a requirement to have this passable by a CLI flag also? I ask as I want to keep the CLI as clean and small as possible.

**Comment by leeuwenrjj** [comment]
That is great!
I would be fine with just the option to put it in the environment. 

I do not think it is important to have it as a passable flag:
If someone would need to put in on the command line you can just run:
NOMAD_TOKEN=12345 levant deploy foo
