### ISSUE TITLE
Only error messages from the final task in a job are reported.

### ISSUE THREAD

**Issue by dansteen** [jrasell/levant#78]
Given a multi-task job like this:

```
job "test" {
  datacenters = ["awse"]
  type        = "service"

  # set our update policy
  update {
    max_parallel     = 1
    health_check     = "checks"
    min_healthy_time = "30s"
    healthy_deadline = "3m"
    auto_revert      = false

    #canary           = 1
    #stagger          = "30s"
  }

  group "jobs" {
    # set our restart policy
    restart {
      interval = "1m"
      attempts = 1
      delay    = "15s"
      mode     = "delay"
    }

    count = 1

    task "first" {
      leader = true

      # our image setup
      driver = "exec"

      config {
        command = "fail"
      }

      resources {
        cpu    = 100
        memory = 100
      }
    }

    task "second" {
      # grant access to secrets
      driver = "exec"

      config {
        command = "sleep"
        args    = ["infinity"]
      }

      resources {
        cpu    = 100
        memory = 100
      }
    }
  }
}
```

Only errors from starting the `second` task will be output.  Specifically, the output from the above is:

```
$ levant deploy /tmp/test.nomad    
[INFO] levant/deploy: using dynamic count 1 for job test and group jobs
[INFO] levant/deploy: triggering a deployment of job test
[INFO] levant/deploy: evaluation 795fb11d-0eee-fd87-a4a5-f556fcb06d2b finished successfully
[INFO] levant/deploy: beginning deployment watcher for job test
[ERROR] levant/deploy: deployment 61e86125-6705-d5e6-05bf-3b4b7635f49b has status failed
[ERROR] levant/failure_inspector: alloc b420f331-a0ef-ea59-2fae-cac85a158138 incurred event sibling task failed because task's sibling "first" failed
[ERROR] levant/failure_inspector: alloc b420f331-a0ef-ea59-2fae-cac85a158138 incurred event driver failure because failed to start task "first" for alloc "b420f331-a0ef-ea59-2fae-cac85a158138": binary "fail" could not be found
[ERROR] levant/failure_inspector: alloc b420f331-a0ef-ea59-2fae-cac85a158138 incurred event not restarting because Error was unrecoverable
[INFO] levant/auto_revert: job test is not in auto-revert; POTENTIAL OUTAGE SITUATION
[ERROR] levant/command: deployment of job test failed
```

Notice that it says `alloc b420f331-a0ef-ea59-2fae-cac85a158138 incurred event sibling task failed because task's sibling "first" failed` but it doesn't actually show any logs from that `first` task.

In this case we get a message because the `first` task was set as the `leader` so the second task failed also, however, if it was *just* the first task that failed no logs or allocation listsings would be output at all.

Thanks!

**Comment by jrasell** [comment]
Hey @dansteen, could you paste the output of the `nomad status test` command which resulted in the failure?

**Comment by dansteen** [comment]
Here is the output of  `nomad status test`:

``` nomad_stag job status test                                                                                       
ID            = test
Name          = test
Submit Date   = 01/02/18 16:37:06 EST
Type          = service
Priority      = 50
Datacenters   = awse
Status        = dead
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
jobs        0       0         0        5       2         0

Latest Deployment
ID          = 61e86125
Status      = failed
Description = Failed due to unhealthy allocations

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy
jobs        1        1       0        1

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created     Modified
b420f331  31ff8691  jobs        6        run      failed    40m10s ago  39m41s ago
36655c80  0c913dd4  jobs        5        run      failed    51m9s ago   50m58s ago
7d248b91  0c01f3c6  jobs        4        run      failed    52m59s ago  52m54s ago
14fe8d8a  1fe66cb1  jobs        3        stop     complete  56m17s ago  52m59s ago
e74e222d  31ff8691  jobs        2        stop     complete  1h45m ago   56m17s ago
47a97e6b  31ff8691  jobs        1        run      failed    1h52m ago   1h51m ago
f8a1af2e  3f09d53e  jobs        0        run      failed    1h54m ago   1h53m ago
```

And here is the output of the allocation:
```
nomad_stag alloc-status b420f331                                                                                      dsteen linux ~.
ID                  = b420f331
Eval ID             = e66e1cf6
Name                = test.jobs[0]
Node ID             = 31ff8691
Job ID              = test
Job Version         = 6
Client Status       = failed
Client Description  = <none>
Desired Status      = run
Desired Description = <none>
Created             = 41m37s ago
Modified            = 41m8s ago
Deployment ID       = 61e86125
Deployment Health   = unhealthy

Task "first" is "dead"
Task Resources
CPU      Memory   Disk     IOPS  Addresses
100 MHz  100 MiB  300 MiB  0

Task Events:
Started At     = N/A
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                   Type            Description
01/02/18 16:37:35 EST  Not Restarting  Error was unrecoverable
01/02/18 16:37:35 EST  Driver Failure  failed to start task "first" for alloc "b420f331-a0ef-ea59-2fae-cac85a158138": binary "fail" could not be found
01/02/18 16:37:07 EST  Task Setup      Building Task Directory
01/02/18 16:37:07 EST  Received        Task received by client

Task "second" is "dead"
Task Resources
CPU      Memory   Disk     IOPS  Addresses
100 MHz  100 MiB  300 MiB  0

Task Events:
Started At     = N/A
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                   Type                 Description
01/02/18 16:37:35 EST  Sibling Task Failed  Task's sibling "first" failed
01/02/18 16:37:07 EST  Task Setup           Building Task Directory
01/02/18 16:37:07 EST  Received             Task received by client
```

It's true that its just a single allocation, but logs and such are actually stored independently.   But it does seem like you are getting logs from both tasks.  It's a bit confusing since they are interspersed.
Also, I do still have the issue where it won't report any logs if it's only the first job that failed.  Let me put together a task that will reproduce that.

**Comment by dansteen** [comment]
Ok.  Figured this out.   In a case where a deployment has failed because services were not available fast enough, but the allocations have not yet failed since they are still in a restart cycle for whatever reason,  levant won't display any logs from the allocation.   This makes sense since the allocations have not actually failed, but I think it would be beneficial to display the allocation ID and some output lines anyway, since, ultimately, its the only real information we can get.

Thanks for your patience with this!

**Comment by jrasell** [comment]
OK, I understand a little better now. For the second issue, if you could open a separate issue that would be appreciated so I can track that.

You are correct in that Levant does not output the logs for each task; currently Levant will only inspect allocations and emit details from those. I guess this would then turn into a feature request to add task log output upon failures?

**Comment by dansteen** [comment]
Sorry, I actually meant allocation details, not logs.   Levant won't emit allocation details for for allocations that have not failed, even though the deployment has failed.   Do you want me to create a separate issue for that?

**Comment by dansteen** [comment]
ok. Some additional details on this.  Basically, if a deployment fails because the service healthchecks have timed out (as defined by [healthy_deadline](https://www.nomadproject.io/docs/job-specification/update.html#healthy_deadline) ), but the allocations themselves are still restarting due to the [restart](https://www.nomadproject.io/docs/job-specification/restart.html) then messages from those non-failed allocations will not be shown.

**Comment by dansteen** [comment]
Ok. So it looks like the problem is here:

https://github.com/jrasell/levant/blob/aec1b25a853a3095ba0fa2c2ecb4a23a3a0f7aa0/levant/failure_inspector.go#L27

That filters out any allocations that are in the "running" state.  The problem is that allocations that are restarting still show up with a clientStatus of "running".   Ultimately, messages are still filtered out in the `nomadClient.allocInspector` function ([here](https://github.com/jrasell/levant/blob/aec1b25a853a3095ba0fa2c2ecb4a23a3a0f7aa0/levant/failure_inspector.go#L48)), so I don't think removing the "running test" logic will be at all harmful.

**Comment by jrasell** [comment]
I think the problem is trickier than that; I also don't want to run the failure inspector and ultimately log error messages for allocations which are perfectly fine.

 Off the top of my head, maybe there could be some logic around whether the alloc is "running" but has incurred a restart in the last n seconds?

**Comment by dansteen** [comment]
Something like that could work.  How about if we look for allocation tasks that the most recent event is not "Started" and then report those?

I think "n seconds" would be a problem since exactly how long nomad should wait before restarting or failing or whatever is configurable by the job.

**Comment by dansteen** [comment]
How about something like this:
```
   // Iterate the allocations on the deployment and create a list of each allocID
   // we only list the ones that have tasks that are not successful
    for _, alloc := range allocs {
     for _, task := range alloc.TaskStates {
       if task.State != "Started" {
         allocIDS = append(allocIDS, alloc.ID)
         // once we add the allocation we don't need to add it again
         break
       }
      }
    }
```

**Comment by dansteen** [comment]
I created a pull request for this since it's probably easier to work there then in the comments :-)
