### ISSUE TITLE
Batch jobs *do* get evaluations on registration

### ISSUE THREAD

**Issue by dansteen** [jrasell/levant#86]
https://github.com/jrasell/levant/pull/52 reports that evaluations are not created for batch jobs on registration.   This is only the case for *paramaterized* batch jobs.   All other types of batch jobs do get evaluations on registration (including periodic jobs).   This has led to some uneccesary limits and code fragmentation with regard to handling batch jobs.

**Comment by jrasell** [comment]
hey @dansteen I believe this is correct apart from the periodic jobs as when testing with the following example job I do not get an evaluation associated:

```
job "periodic_test" {
  datacenters = ["dc1"]
  region      = "global"
  type        = "batch"
  priority    = 75
  periodic {
    cron             = "* * * * * *"
    prohibit_overlap = true
  }
  group "periodic" {
    task "periodic" {
      driver = "docker"
      config {
        image = "cogniteev/echo"
      }
      resources {
        cpu    = 100
        memory = 128
        network {
          mbits = 1
        }
      }
    }
  }
}
```
