### ISSUE TITLE
multi-line environment variables result in an error by levant but are accepted by nomad

### ISSUE THREAD

**Issue by dansteen** [jrasell/levant#88]
**Description**
The following `env` is correctly interpreted by  nomad, but results in an error in levant.  

```
env {
        CHEF_ENV = "${meta.env}"
        APP_NAME = "api"
        IP_ADDRESS = "${attr.unique.platform.aws.public-ipv4}"
        LOCAL_HOSTNAME = "${node.unique.name}"
        JAVA_TOOL_OPTIONS = "-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.port=${NOMAD_PORT_jmx}
-Dcom.sun.management.jmxremote.local.only=true
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false 
-Djava.rmi.server.hostname=localhost 
-Dnetworkaddress.cache.ttl=60 
-Xms1024M 
-XX:-UseConcMarkSweepGC 
-Xmx1024M"
}
```
Nomad has no trouble with this.  Levant generates the following error:
`[ERROR] levant/command: error parsing: At 62:61: literal not terminated`

Levant seems to error out on the carriage returns in the `JAVA_TOOL_OPTIONS` env variable.

**Comment by dansteen** [comment]
So, looking more closely at the HCL spec, it says the following items:

1. Values are assigned with the syntax key = value (whitespace doesn't matter). The value can be any primitive: a string, number, boolean, object, or list.
1. Strings are double-quoted and can contain any UTF-8 characters. Example: "Hello, World"
1.  Multi-line strings start with <<EOF at the end of a line, and end with EOF on its own line (here documents). Any text may be used in place of EOF. 

So  this does seem to sort of contradict itself since item 1 above says that "whitespace doesn't matter", and 2 above says that any UTF-8 character can be included (including carriage returns).   However,  3 above indicates that you can't have multi-line strings which would exclude carriage returns.   

Ultimately, however, https://github.com/hashicorp/hcl/issues/211 discusses something like this, and indicates that they did not intend for multi-line strings outside of heredocs to be supported for now.   So I think that even though  nomad itself supports the syntax mentioned in the issue, this is an error, and will not be supported at some point going forward.   

So I think we can close this as being the correct behavior.

**Comment by jrasell** [comment]
hey @dansteen thanks for the investigation into this.
